### PR TITLE
Use shifted beta-values in screening

### PR DESCRIPTION
**Pull request by nhejazi**

### CODE REVIEW

**Comment by nhejazi** [comment]
👋 @rachaelvphillips, I believe that the substantive contribution stems from either code or ideas originally contributed by you. If this is indeed the case, would you mind confirming whether the use of the packages [`Harman`](https://bioconductor.org/packages/Harman) and [`lumi`](https://bioconductor.org/packages/lumi) in the filtering function `limma_screen` is something we wanted to keep? Currently, it appears that their use here is to shift Beta-values (when these are the input) in an attempt to improve the filtering process; however, their use also appears to cause an error, where, in some cases, the transformed values are mapped to unusable values like `Inf`.

**Comment by rachaelvphillips** [comment]
Hi @nhejazi, 
By "transformed values being mapped to unusable values like `Inf`" do you mean that the transformed *Beta* values being mapped to unusable *M-*values like `Inf`? 

Ironically, this functionality is inteneded to prevent unusable `Inf` and `-Inf` M-values. `Harman::shiftBetas` shifts Beta values of exactly 0 or 1 by a very small amount (typically 1 x 10^-4) assuring that there are no Inf and -Inf values in the M-value matrix.

**Comment by nhejazi** [comment]
Thanks for the prompt reply. It looks like the current use of this combination of functions from `Harman` and `lumi` is causing a failure in the unit test(s) for the function `limma_screen`, which appears [here](). Below is the error that arises in an interactive R session when running through that unit test:

```r
✔  methyvim shiftBetas
❯ screened_betas <- methyvim:::limma_screen(methytmle,
...   var_int = var_int,
...   type = "Beta"
... )
Error in is.nan(betas) : default method not implemented for type 'S4'

✔  methyvim shiftBetas
❯ traceback()
2: Harman::shiftBetas(betas, shiftBy = 0.001) at screen_limma.R#45
1: methyvim:::limma_screen(methytmle, var_int = var_int, type = "Beta")
```

**Comment by nhejazi** [comment]
Closing for now, since this has become stale. We can re-visit/re-open this if it becomes relevant again.

**Pull request closed without merging**
